#---- AMAPOLA2SC.py : Update polarization data in the Source Catalogue (SC)
# Description:
#  This script reads AMAPOLA results of the specified ExecBlock UID and update 'angle', 'angleUncertainty', 'degree', 'degreeUncertainty' entries in the SC.
#  Other items are preserved.
# 
# Usage:
#  python AMAPOLA2SC.py -u [ExecBlock UID]
#  e.g. : python SC_fetchUID.py -u uid://A002/X13cdcf8/X12478
#
# Requirements:
#  + Base64 Credential of username and password must be set as 'b64credentials' environmental variable.
#  + ROLE_SOURCECAT_ADMIN privileges must be given, in advance. See https://confluence.alma.cl/x/G2BiBQ
#
# Notes:
#  + AMAPOLA_URI is planned to move to ICT control in the year 2027.
#
import os
import re
import numpy as np
import ssl
import json
import urllib
from urllib.request import urlopen
import http.client as httplib
from optparse import OptionParser
#-------- Parse options
parser = OptionParser()
parser.add_option('-u',  dest='uid', metavar='uid', help='UID to Ingest e.g. uid___A002_X10ded83_Xa91e', default='')
(options, args) = parser.parse_args()
AMAPOLA_PATH = '/users/skameno/ALMAR/WORK/'
AMAPOLA_URI = 'https://www.alma.cl/~skameno/Grid/Stokes/'
SC_URI = 'https://sourcecat.osf.alma.cl/sc/rest/'
URI_EB = SC_URI + 'measurements?limit=256&execblockUid='
UserPass = os.getenv('b64credentials', '')  # Authorization Basic Base64
if len(UserPass) < 8:                       # Check Authorization
    print('Set Base64 Credential to the environmental variable \'b64credentials\'\n')
    exit()
#-------- Parse AMAPOLA LOG
def AMAPOLA_IQUV( logLines ):
    # logLines : AMAPOLA Log file on the web
    # output   : dictionary that records Stokes parameters
    #---- find source name
    logList = [log.decode('utf-8').strip() for log in logLines]
    sourceList = [log.split()[1] for log in logList if 'EL=' in log]
    QSOList = [source for source in sourceList if source[0] == 'J']
    StokesDic = dict(zip(QSOList, [[]]*len(QSOList)))
    for QSO in QSOList:
        QSOLines = [log_index for log_index,log in enumerate(logList) if QSO in log]
        for QSOblock in QSOLines:
            lineIndex = QSOblock
            HeadWords = logList[lineIndex].split()
            EL = [float(word.split('=')[1]) for word in HeadWords if 'EL=' in word][0]
            DT = [word for word in HeadWords if '/' in word][0]
            while 'GHz' not in logList[lineIndex]: lineIndex += 1
            freqList, IList, QList, UList, VList, eIList, eQList, eUList, eVList = [], [], [], [], [], [], [], [], []
            while 'GHz' in logList[lineIndex]:
                EntryValues = [value for value in re.split(r'\s+|GHz|\(|\)', logList[lineIndex]) if value]
                freqList = freqList + [float(EntryValues[1])]
                IList = IList + [float(EntryValues[2])]
                QList = QList + [float(EntryValues[4])]
                UList = UList + [float(EntryValues[6])]
                VList = VList + [float(EntryValues[8])]
                eIList = eIList + [float(EntryValues[3])]
                eQList = eQList + [float(EntryValues[5])]
                eUList = eUList + [float(EntryValues[7])]
                eVList = eVList + [float(EntryValues[9])]
                lineIndex += 1
            #
            StokesDic[QSO] = {
                'EL':       EL,
                'DT':       DT,
                'freqency': np.array(freqList),
                'I':        np.array(IList),
                'Q':        np.array(QList),
                'U':        np.array(UList),
                'V':        np.array(VList),
                'eI':       np.array(eIList),
                'eQ':       np.array(eQList),
                'eU':       np.array(eUList),
                'eV':       np.array(eVList)}
    return StokesDic
#
def fluxInterpolate( srcDic, src, refFreq ):
    # srcDic : dictionary generated by AMAPOLA_IQUV
    # src    : source name to investigate
    # refFreq: frequency to estimate I, Q, U, V
    # output : estimated Stokes parameters at the given frequency, with error
    if src not in srcDic.keys(): return
    relFreq = (srcDic[src]['freqency'] - refFreq)/ refFreq
    #---- Stoes Parameters
    StokesComponents, StokesValues, StokesErrors = ['I', 'Q', 'U', 'V'], [], []
    for Stokes in StokesComponents:
        coef, cov = np.polyfit(relFreq, srcDic[src][Stokes], deg=1, w=1.0/srcDic[src]['e'+Stokes], cov=True)
        StokesValues = StokesValues + [coef[1]]
        StokesErrors = StokesErrors + [np.sqrt(cov[1,1])]
    return np.array([StokesValues,StokesErrors])
#
prefix = options.uid.replace("/", "_").replace(":","_").replace(" ","")
#prefix = 'uid___A002_X13cdcf8_X12478'
EB  = prefix.replace("___", "://").replace("_","/")
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE
url = URI_EB + EB
jdata = urlopen(url, context=ctx).read()
dataList = json.loads(jdata)
bandList = list(set([int(data['bandName'].split()[1]) for data in dataList]))
#
if len(dataList) == 0:
    print('%s is not recorded in the source catalogue' % (EB))
    exit()
print('%s Band%d in AMAPOLA' % (EB, bandList[0]))
conn = httplib.HTTPSConnection("sourcecat.osf.alma.cl",context=ssl._create_unverified_context())
#-------- Load AMAPOLA results
for band in bandList:
    AMAPOLA_fileName = '%s-RB_%02d-Flux.log' % (prefix, band)
    amapolaLOG = urlopen(AMAPOLA_URI + AMAPOLA_fileName).readlines()
    StokesDic = AMAPOLA_IQUV(amapolaLOG)    
print('Source       Frequency    I [Jy]         Q [Jy]         U [Jy]         V [Jy]          p [%]           EVPA [deg]')
for data in dataList:
    StokesValues = fluxInterpolate( StokesDic, data['names'][0]['name'], 1.0e-9* data['frequency'] )
    I = StokesValues[0,0]
    Psqr = StokesValues[0,1]**2 + StokesValues[0,2]**2
    Pdeg = 100.0*np.sqrt(Psqr) / I
    ePdeg= 100.0*np.sqrt((StokesValues[0,1]**2 * StokesValues[1,1]**2 + StokesValues[0,2]**2 * StokesValues[1,2]**2)/ Psqr + (Psqr* StokesValues[1,0]**2)/I**2 )/I 
    Pang = 90.0* np.arctan2(StokesValues[0,2],StokesValues[0,1])/np.pi
    ePang= 90.0* np.sqrt(StokesValues[0,1]**2 * StokesValues[1,2]**2 + StokesValues[0,2]**2 * StokesValues[1,1]**2) / Psqr / np.pi
    print('%s : %.1f GHz : %6.3f (%.3f) %+.3f (%.3f) %+.3f (%.3f) %+.3f (%.3f)  %6.3f (%.3f)  %+7.3f (%.3f)' % (data['names'][0]['name'], 1.0e-9* data['frequency'],
        StokesValues[0,0], StokesValues[1,0],
        StokesValues[0,1], StokesValues[1,1],
        StokesValues[0,2], StokesValues[1,2],
        StokesValues[0,3], StokesValues[1,3],
        Pdeg, ePdeg,
        Pang, ePang))
    #---- Check consistency in Stokes I
    if abs(StokesValues[0,0] - data['flux']) > 0.2* data['flux']: continue  # Filter >20% discrepancy out
    #---- Post polarization data to SC
    urlPart = '/sc/rest/measurements/%d/update?degree=%.3f&degreeUncertainty=%.3f&angle=%.3f&angleUncertainty=%.3f' % (data['id'], Pdeg, ePdeg, Pang, ePang)
    conn.putrequest('POST', urlPart);
    conn.putheader('Authorization', 'Basic %s' % (UserPass))
    conn.endheaders()
    resp = conn.getresponse()
    if resp.status == 200:
        success = resp.read()
        if json.loads(success):
            print('Succeeded to update : measurementID = %d : %s' % (data['id'], urlPart))
        else:
            print('Faild to ingest : %s' % (urlPart))
    else:
        print('Faild to ingest : %s' % (urlPart))
#
